---
- name: Add Nginx signing key
  apt_key: 
    url: http://nginx.org/packages/keys/nginx_signing.key 
    state: present

- name: Adding sources.list.d deb url for NGINX
  apt_repository: 
    repo: deb http://nginx.org/packages/ubuntu/ trusty nginx 
    state: present 
    filename: nginx 
    update_cache: yes

- name: Install Nginx
  apt:
    name: nginx
    state: present
    force: yes
    update_cache: yes
  notify: restart nginx
