- name: change apt repo to mirror.kku.ac.th
  replace:
    path: /etc/apt/sources.list
    regexp: 'http:\/\/(?!archive.canonical.com).*\/ubuntu'
    replace: 'http://mirror.kku.ac.th/ubuntu'

- name: update/upgrade packages
  apt:
    update_cache: true
    upgrade: safe
    cache_valid_time: 604800 # 1 week

- name: ssh server UseDNS no
  lineinfile: path=/etc/ssh/sshd_config line="UseDNS no"
  notify: restart ssh

- include: locale.yml

- name: install common packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
    - nano
    - nload
    - htop
    - iotop
    - zip
    - unzip
    - apt-transport-https
    - ca-certificates

- include: ntpdate.yml
