---
- name: update packages
  apt: update_cache=yes

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - vim
  - nano
  - nload
  - python-pip
  - htop
  - munin-node
  - zip
  - unzip
  - apt-transport-https
  - ca-certificates
  - ntpdate

- name: Update the /etc/ssh/sshd_config file
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^UseDNS"
    line: "UseDNS no"
    insertafter: EOF
    state: present
  register: ssh_config

- name: Restart ssh
  service:
    name: ssh
    state: restarted
  when: ssh_config.changed

- name: Upadate the /etc/default/locale file
  lineinfile:
    dest: /etc/default/locale
    regexp: "^LC_ALL="
    line: 'LC_ALL="en_US.UTF-8"'
    insertafter: EOF

- name: Gen locale
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Create cron ntpdate
  cron:
    name: "ntpdate"
    user: "root"
    hour: "*/8"
    job: "/usr/sbin/ntpdate time.navy.mi.th >> /tmp/ntpdate.log 2>&1"
    cron_file: "auto-ntpdate"
